# Generated by Django 3.1.7 on 2021-03-28 22:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import root.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=255)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('image_description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(default='/no_image.jpeg', upload_to=root.models.assetSaver)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_url', models.CharField(blank=True, max_length=255, unique=True)),
                ('post_content', models.TextField()),
                ('post_image', models.ImageField(default='/no_image.jpg', upload_to=root.models.assetSaver)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='phoneClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('geo_location', models.CharField(max_length=255)),
                ('click_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='seoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField(default='pas de contenu..')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=255, unique=True)),
                ('service_url', models.CharField(blank=True, max_length=255, unique=True)),
                ('service_meta_title', models.CharField(blank=True, max_length=60)),
                ('service_meta_description', models.CharField(blank=True, max_length=160)),
                ('service_content', models.TextField(default='pas de contenu..')),
                ('service_image', models.ImageField(default='/no_service.jpg', upload_to=root.models.assetSaver)),
                ('service_image_alt', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message="Merci d'entrer un numéro de téléphone valide, comme : (0123456789 or +1234567890)", regex='^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$')])),
                ('nom_sur_site', models.CharField(max_length=10)),
                ('adresse_local', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to=root.models.faviconGenerator)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number like : (0123456789 or +1234567890)', regex='^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$')])),
                ('mail', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('interestedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.service')),
            ],
        ),
    ]
