# Generated by Django 3.1.7 on 2021-03-16 06:20

from django.db import migrations, models
import root.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=255)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('image_description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(default='storage/no_image.jpeg', upload_to=root.models.assetSaver)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=255, unique=True)),
                ('service_url', models.CharField(blank=True, max_length=255, unique=True)),
                ('service_meta_title', models.CharField(blank=True, max_length=255)),
                ('service_meta_description', models.CharField(blank=True, max_length=255)),
                ('service_content', models.TextField(default='pas de contenu..')),
                ('service_image', models.ImageField(default='/no_service.jpg', upload_to=root.models.assetSaver)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_password', models.CharField(max_length=50)),
            ],
        ),
    ]
