# Generated by Django 3.1.7 on 2021-03-22 19:36

from django.db import migrations, models
import root.models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='/no_image.jpeg', upload_to=root.models.assetSaver),
        ),
    ]
