# Generated by Django 3.1.7 on 2021-04-17 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_maintenance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='maintenance',
        ),
    ]
