# Generated by Django 3.1.7 on 2021-03-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_seolinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seoLinks',
        ),
    ]
