# Generated by Django 3.1.7 on 2021-05-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_gitaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gitAccount',
        ),
    ]
