# Generated by Django 3.1.7 on 2021-03-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_seolinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seolinks',
            name='url',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
