# Generated by Django 3.1.7 on 2021-03-23 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20210322_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('mail', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('interestedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.service')),
            ],
        ),
    ]
