# Generated by Django 3.1.7 on 2021-03-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
