# Generated by Django 3.1.7 on 2021-05-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_pagecontent_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
