# Generated by Django 3.1.7 on 2021-05-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_auto_20210516_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=models.TextField(),
        ),
    ]
