# Generated by Django 3.1.7 on 2021-05-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_auto_20210516_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='page',
            name='page_meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
