# Generated by Django 3.1.7 on 2021-05-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_auto_20210516_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_meta_description',
            field=models.TextField(blank=True, max_length=160),
        ),
    ]
