# Generated by Django 3.1.7 on 2021-05-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_auto_20210516_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='page',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
